AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an EC2 instance to run static web site with Apache web server
  
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: cumhurkey
      SecurityGroups:
        - http-ssh-sec-group
      Tags:
        - Key: Name 
          Value: Web Server of StackName
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          yum install git -y 
          chmod -R 777 /var/www/html
          cd /var/www/html/
          git clone https://github.com/cmakkaya/Project-101-kittens-carousel-static-website-ec2-with-automatic-update.git
          cd Project-101-kittens-carousel-static-website-ec2-with-automatic-update/
          cp * ../
          cd ../
          rm -rf Project-101-kittens-carousel-static-website-ec2-with-automatic-update/
          wget https://raw.githubusercontent.com/cmakkaya/01.my-projects_bash_script/main/autogitpull-on-ec2.sh
          crontab<<EOF
          * * * * * /var/www/html/autogitpull-on-ec2.sh
          EOF